### ISSUE TITLE
Difference between BLOCK and GROUP?

### ISSUE THREAD

**Issue by Erland366** [BobMcDear/attorch#3]
Hello, I am always really interested in Triton and GPU programming. I just starting to learn about them actually. I stumbled upon your project and first of all, Attorch is really really awesome and thank you for creating and opening this awesome project!

Currently, I am trying to understand the code, and I saw this `GROUP` concept which I having a hard time imagining this and why we need it to parallelize the kernel. For me, they pretty similar to `BLOCK` (based on the naming too :D). Perhaps can you explain of what's GROUP in Triton or in GPU programming in general?

Thank you in advance!

**Comment by BobMcDear** [comment]
Hello,

Glad to hear of your interest in GPU programming! Suppose we would like to determine the product ```C``` of two matrices of shape ```[4, 4]```, ```A``` and ```B```, in 4 iterations, each calculating 4 elements. Taking the first iteration as a concrete example, it can either compute the first row of ```C``` , or alternatively, we have the option to split ```C``` into 4 contiguous non-overlapping sub-matrices of shape ```[2, 2]``` and calculate the first group in the first iteration. The first approach, which utilizes linear ordering, would involve loading the first row of ```A``` and the entirety of ```B``` (a total of 20 = 4 + 4 * 4 elements), whereas the second, which utilizes grouped or swizzled ordering, requires loading the first two rows of ```A``` and the first two columns of ```B``` (a total of 16 = 2 * 4 + 4 * 2 elements) and is thus more efficient. A visualization of both methods for larger matrices from [Triton's tutorial on matrix multiplication](https://triton-lang.org/main/getting-started/tutorials/03-matrix-multiplication.html#l2-cache-optimizations) can be seen below.

<img width="673" alt="grouped_vs_row_major_ordering" src="https://github.com/BobMcDear/attorch/assets/62210058/aff0b24c-77e8-417e-90c0-3072fd6e8b37">

Note that grouping does not really affect kernel parallelization; rather, it alters the ordering of computations.

**Comment by Erland366** [comment]
So can I think of `GROUP` as a group of blocks that we want to load? So the hierarchy would be `GROUP` -> `BLOCK` -> `THREAD`? 

The main motivation of why we would want to `GROUP` things if we want to be a little smart of the calculation (in this case, we were able to reduce the amount of load because it matmul, we don't have to take all the entirety of `B`)? Say for example we just want to parallelize convolution where we just spawn number of threads based on the number of output pixels, we didn't have to think about `GROUP` right?

Also, isn't this matmul example pretty similar with `TILING`? can we think `GROUP` as a `TILE`? 

Btw thank you so much for your respond and sorry for my very late response :(

**Comment by BobMcDear** [comment]
> So can I think of GROUP as a group of blocks that we want to load? So the hierarchy would be GROUP -> BLOCK -> THREAD?

Sort of. A group can be thought of as a sub-matrix of the output, and multiple blocks will be tasked with computing one output group. However, groups are not actually computing anything; they are an abstraction that modify the ordering of block computations (see the formulas for ```batch_pid``` and ```out_feat_pid```).

> The main motivation of why we would want to GROUP things if we want to be a little smart of the calculation (in this case, we were able to reduce the amount of load because it matmul, we don't have to take all the entirety of B)

Yes, grouping promotes data reuse and improves the L2 cache hit ratio.

>  Say for example we just want to parallelize convolution where we just spawn number of threads based on the number of output pixels, we didn't have to think about GROUP right?

Grouping is not necessary for convolutions, but bear in mind that kernels for convolutions are not as straightforward as assigning a thread to each output pixel.

> Also, isn't this matmul example pretty similar with TILING? can we think GROUP as a TILE?

Essentially, yes - grouping launches blocks in a tiled rather than linear order.

**Comment by Erland366** [comment]
Sorry for the very late reply. Been very busy last week 😅. Thank you so much for answering my question! I think I am starting to understand the structure and the combination etc. Your explanation is very very helpful 😄
