### ISSUE TITLE
the model inference speed

### ISSUE THREAD

**Issue by LHW-CLOUD** [BobMcDear/attorch#4]
Why does the model inference speed become very slow after converting the model operator into the Triton form。I don't know if it's due to caching

**Comment by LHW-CLOUD** [comment]
Thanks a lot! I seem to have noticed a previous issue where there was a logical error in my code. But I have a new question to ask you. I want to save Triton ir now, and I found that the Triton compiler defaults to saving all intermediate files under       
      /home/. triton/dump  It seems that each folder corresponds to the intermediate representation of an operator (I don't know if my understanding is correct). Is there a way to integrate all IR files into one IR file and use this complete IR file to run the inference results of the model?  Thank you！

**Comment by BobMcDear** [comment]
I am unfortunately ill-equipped to answer your question as I have not worked with Triton IR in the past. I suggest you [open up an issue](https://github.com/triton-lang/triton/issues/new) on the Triton repository since this issue does not directly concern attorch.

**Comment by LHW-CLOUD** [comment]
thank you！
